### ISSUE TITLE
 php 7.3 issue

### ISSUE THREAD

**Issue by gaborbit** [allebb/gpio#1]
Hello
I tried to install via composer and got this message

```
Installation failed, deleting ./composer.json.
  [ErrorException]
  "continue" targeting switch is equivalent to "break". Did you mean to use "
  continue 2"?
```

**Comment by gaborbit** [comment]
Sorry it was my mistake.
I had to reinstall composer
```
$ curl -sS https://getcomposer.org/installer | php
$ sudo mv composer.phar /usr/bin/composer
```
Check if went well with
`composer --version`

**Comment by allebb** [comment]
Excellent news :) - I was going to say that the builds for PHP 7.3 are
running and passing fine :)

I'm pleased that it was just a mistake.

Best of luck with your project!

Regards,
Bobby
